name: Deploy

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest code
        run: git pull origin main
      - name: Deploy containers
        run: docker-compose up -d
